# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import adafruit_pb2 as adafruit__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


class AHT20Stub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Measure = channel.unary_unary(
                '/adafruit.AHT20/Measure',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=adafruit__pb2.AHT20Reply.FromString,
                )


class AHT20Servicer(object):
    """Missing associated documentation comment in .proto file."""

    def Measure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AHT20Servicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Measure': grpc.unary_unary_rpc_method_handler(
                    servicer.Measure,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=adafruit__pb2.AHT20Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'adafruit.AHT20', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AHT20(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Measure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/adafruit.AHT20/Measure',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            adafruit__pb2.AHT20Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
