# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: adafruit.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='adafruit.proto',
  package='adafruit',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x61\x64\x61\x66ruit.proto\x12\x08\x61\x64\x61\x66ruit\x1a\x1bgoogle/protobuf/empty.proto\"<\n\nAHT20Reply\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x19\n\x11relative_humidity\x18\x02 \x01(\x02\x32\x42\n\x05\x41HT20\x12\x39\n\x07Measure\x12\x16.google.protobuf.Empty\x1a\x14.adafruit.AHT20Reply\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_AHT20REPLY = _descriptor.Descriptor(
  name='AHT20Reply',
  full_name='adafruit.AHT20Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature', full_name='adafruit.AHT20Reply.temperature', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relative_humidity', full_name='adafruit.AHT20Reply.relative_humidity', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=117,
)

DESCRIPTOR.message_types_by_name['AHT20Reply'] = _AHT20REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AHT20Reply = _reflection.GeneratedProtocolMessageType('AHT20Reply', (_message.Message,), {
  'DESCRIPTOR' : _AHT20REPLY,
  '__module__' : 'adafruit_pb2'
  # @@protoc_insertion_point(class_scope:adafruit.AHT20Reply)
  })
_sym_db.RegisterMessage(AHT20Reply)



_AHT20 = _descriptor.ServiceDescriptor(
  name='AHT20',
  full_name='adafruit.AHT20',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=119,
  serialized_end=185,
  methods=[
  _descriptor.MethodDescriptor(
    name='Measure',
    full_name='adafruit.AHT20.Measure',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_AHT20REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_AHT20)

DESCRIPTOR.services_by_name['AHT20'] = _AHT20

# @@protoc_insertion_point(module_scope)
